heat_template_version: ocata

parameters:
  public_net_id:
    type: string

resources:

  network:
    type: OS::Neutron::Net
  subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: network }
      enable_dhcp: true
      cidr: '10.10.0.0/24'
      dns_nameservers:
      #        - 172.18.224.6
      #        - 172.18.176.6
        - 8.8.8.8
        - 8.8.4.4
  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net_id }
  router_iface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: subnet }


outputs:
  public_network:
    value: { get_resource: network }
  accessible_subnet_id:
    value: { get_resource: subnet }
